- name: configure httpd service
  hosts: all
  remote_user: devops
  become: True
  tasks:
  - name: Install httpd service
    yum:
      name: httpd
      state: installed
  
  - name: Install mod_ssl 
    yum:
      name: mod_ssl
      state: latest

  - name: copy index.html to doc root of httpd
    copy:
      src: index.html
      dest: /var/www/html/index.html

  - name: Install firewalld
    yum:
      name: firewalld
      state: installed

  - name: Start httpd service
    service:
      name: httpd
      state: started
      enabled: yes

  - name: Start firewalld service
    service:
      name: firewalld
      state: started
      enabled: yes

  - name: configure firewalld for httpd
    firewalld:
      service: http
      state: enabled
      immediate: yes
      permanent: yes
  
  - name: configure firewalld for httpd
    firewalld:
      service: https
      state: enabled
      immediate: yes
      permanent: yes
